apiVersion: apps/v1
kind: Deployment
metadata:
  name: taski-devops-app
  labels:
    app: taski-devops-app
    environment: production

spec:
  replicas: 2
  selector:
    matchLabels:
      app: taski-devops-app

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  template:
    metadata:
      labels:
        app: taski-devops-app
    spec:
      containers:
        - name: taski-devops-app
          image: kumaravelan/taski-devops-app:IMAGE_TAG
          ports:
            - containerPort: 3000

          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3000"
            - name: APP_VERSION
              value: "1.0.0"

# health checks

          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3

# Resource Limits

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"



