apiVersion: v1
kind: Service
metadata:
  name: taski-devops-app-service
  labels:
    app: taski-devops-app

spec:
  type: LoadBalancer
  selector:
    app: taski-devops-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000