pipeline {
    agent any

    environment {
        APP_NAME        = 'taski-devops-app'
        DOCKER_IMAGE    = "kumaravelan/${APP_NAME}"
        DOCKER_TAG      = "${BUILD_NUMBER}"
        DOCKER_CREDS    = credentials('dockerhub-credentials')
    }

    stages {

        stage('Checkout') {
            steps {
                echo ' Checking out source code...'
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                echo ' Installing dependencies...'
                dir('app') {
                    sh 'npm install'
                }
            }
        }

        stage('Test') {
            steps {
                echo ' Running tests...'
                dir('app') {
                    sh 'npm test'
                }
            }
        }

        stage('Security Scan') {
            steps {
                echo ' Running security scan...'
                dir('app') {
                    sh 'npm audit --audit-level=high || true'
                }
            }
        }

        stage('Docker Build') {
            steps {
                echo ' Building Docker image...'
                dir('app') {
                    sh """
                        docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} .
                        docker tag ${DOCKER_IMAGE}:${DOCKER_TAG} ${DOCKER_IMAGE}:latest
                    """
                }
            }
        }

        stage('Docker Push') {
            steps {
                echo ' Pushing image to DockerHub...'
                sh """
                    echo $DOCKER_CREDS_PSW | docker login -u $DOCKER_CREDS_USR --password-stdin
                    docker push ${DOCKER_IMAGE}:${DOCKER_TAG}
                    docker push ${DOCKER_IMAGE}:latest
                """
            }
        }

    }

    post {
        success {
            echo ' Pipeline SUCCESS! Image pushed to DockerHub!'
        }
        failure {
            echo '❌ Pipeline FAILED! Check logs above.'
        }
        always {
            sh """
                docker rmi ${DOCKER_IMAGE}:${DOCKER_TAG} || true
                docker rmi ${DOCKER_IMAGE}:latest || true
            """
        }
    }
}